[package]
name = "textured_cube"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.18"
winit = "0.28"
env_logger = "0.10"
log = "0.4"
cgmath = "0.18"
image = "0.24"
bytemuck = { version = "1.12", features = ["derive"] }
pollster = "0.3"