[package]
name = "textured_cube"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.20"
winit = "0.29"
env_logger = "0.11"
log = "0.4"
cgmath = "0.18"
image = "0.25"
bytemuck = { version = "1.12", features = ["derive"] }
pollster = "0.3"